//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company_tempbill
    {
        public string Company_Name { get; set; }
        public Nullable<decimal> Weights { get; set; }
        public string Fabric { get; set; }
        public Nullable<decimal> rate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string TotlaAmount { get; set; }
        public string maker_by { get; set; }
        public Nullable<System.DateTime> mk_dt { get; set; }
        public string roll { get; set; }
        public string Colour { get; set; }
        public string d_date { get; set; }
        public string d_challan_no { get; set; }
        public string rowid { get; set; }
    }
}
