//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FabricEntities : DbContext
    {
        public FabricEntities()
            : base("name=FabricEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company_tempbill> Company_tempbill { get; set; }
        public virtual DbSet<SETUP_COMPANY> SETUP_COMPANY { get; set; }
        public virtual DbSet<temp_bill> temp_bill { get; set; }
    
        public virtual ObjectResult<sp_billPayment_Result> sp_billPayment(string p_CompanyCode, string p_Weight, string p_d_date, string p_challan_no, string p_Colour, string p_fabric, string p_rate, string p_roll, string p_amount, string p_totalamount, string p_User, string p_Maker, string p_Makerdt, string actionType)
        {
            var p_CompanyCodeParameter = p_CompanyCode != null ?
                new ObjectParameter("p_CompanyCode", p_CompanyCode) :
                new ObjectParameter("p_CompanyCode", typeof(string));
    
            var p_WeightParameter = p_Weight != null ?
                new ObjectParameter("p_Weight", p_Weight) :
                new ObjectParameter("p_Weight", typeof(string));
    
            var p_d_dateParameter = p_d_date != null ?
                new ObjectParameter("p_d_date", p_d_date) :
                new ObjectParameter("p_d_date", typeof(string));
    
            var p_challan_noParameter = p_challan_no != null ?
                new ObjectParameter("p_challan_no", p_challan_no) :
                new ObjectParameter("p_challan_no", typeof(string));
    
            var p_ColourParameter = p_Colour != null ?
                new ObjectParameter("p_Colour", p_Colour) :
                new ObjectParameter("p_Colour", typeof(string));
    
            var p_fabricParameter = p_fabric != null ?
                new ObjectParameter("p_fabric", p_fabric) :
                new ObjectParameter("p_fabric", typeof(string));
    
            var p_rateParameter = p_rate != null ?
                new ObjectParameter("p_rate", p_rate) :
                new ObjectParameter("p_rate", typeof(string));
    
            var p_rollParameter = p_roll != null ?
                new ObjectParameter("p_roll", p_roll) :
                new ObjectParameter("p_roll", typeof(string));
    
            var p_amountParameter = p_amount != null ?
                new ObjectParameter("p_amount", p_amount) :
                new ObjectParameter("p_amount", typeof(string));
    
            var p_totalamountParameter = p_totalamount != null ?
                new ObjectParameter("p_totalamount", p_totalamount) :
                new ObjectParameter("p_totalamount", typeof(string));
    
            var p_UserParameter = p_User != null ?
                new ObjectParameter("p_User", p_User) :
                new ObjectParameter("p_User", typeof(string));
    
            var p_MakerParameter = p_Maker != null ?
                new ObjectParameter("p_Maker", p_Maker) :
                new ObjectParameter("p_Maker", typeof(string));
    
            var p_MakerdtParameter = p_Makerdt != null ?
                new ObjectParameter("p_Makerdt", p_Makerdt) :
                new ObjectParameter("p_Makerdt", typeof(string));
    
            var actionTypeParameter = actionType != null ?
                new ObjectParameter("ActionType", actionType) :
                new ObjectParameter("ActionType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_billPayment_Result>("sp_billPayment", p_CompanyCodeParameter, p_WeightParameter, p_d_dateParameter, p_challan_noParameter, p_ColourParameter, p_fabricParameter, p_rateParameter, p_rollParameter, p_amountParameter, p_totalamountParameter, p_UserParameter, p_MakerParameter, p_MakerdtParameter, actionTypeParameter);
        }
    
        public virtual ObjectResult<sp_Company_Result> sp_Company(string p_CompanyCode, string p_CompanyName, string p_Mobile_no, string p_Address, string p_Maker, string p_Makerdt, string actionType)
        {
            var p_CompanyCodeParameter = p_CompanyCode != null ?
                new ObjectParameter("p_CompanyCode", p_CompanyCode) :
                new ObjectParameter("p_CompanyCode", typeof(string));
    
            var p_CompanyNameParameter = p_CompanyName != null ?
                new ObjectParameter("p_CompanyName", p_CompanyName) :
                new ObjectParameter("p_CompanyName", typeof(string));
    
            var p_Mobile_noParameter = p_Mobile_no != null ?
                new ObjectParameter("p_Mobile_no", p_Mobile_no) :
                new ObjectParameter("p_Mobile_no", typeof(string));
    
            var p_AddressParameter = p_Address != null ?
                new ObjectParameter("p_Address", p_Address) :
                new ObjectParameter("p_Address", typeof(string));
    
            var p_MakerParameter = p_Maker != null ?
                new ObjectParameter("p_Maker", p_Maker) :
                new ObjectParameter("p_Maker", typeof(string));
    
            var p_MakerdtParameter = p_Makerdt != null ?
                new ObjectParameter("p_Makerdt", p_Makerdt) :
                new ObjectParameter("p_Makerdt", typeof(string));
    
            var actionTypeParameter = actionType != null ?
                new ObjectParameter("ActionType", actionType) :
                new ObjectParameter("ActionType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Company_Result>("sp_Company", p_CompanyCodeParameter, p_CompanyNameParameter, p_Mobile_noParameter, p_AddressParameter, p_MakerParameter, p_MakerdtParameter, actionTypeParameter);
        }
    
        public virtual ObjectResult<sp_Customer_invoice_Result> sp_Customer_invoice(string p_CompanyCode)
        {
            var p_CompanyCodeParameter = p_CompanyCode != null ?
                new ObjectParameter("p_CompanyCode", p_CompanyCode) :
                new ObjectParameter("p_CompanyCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Customer_invoice_Result>("sp_Customer_invoice", p_CompanyCodeParameter);
        }
    
        public virtual ObjectResult<sp_userlogin_Result> sp_userlogin(string p_userid, string p_password)
        {
            var p_useridParameter = p_userid != null ?
                new ObjectParameter("p_userid", p_userid) :
                new ObjectParameter("p_userid", typeof(string));
    
            var p_passwordParameter = p_password != null ?
                new ObjectParameter("p_password", p_password) :
                new ObjectParameter("p_password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_userlogin_Result>("sp_userlogin", p_useridParameter, p_passwordParameter);
        }
    }
}
