//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class SETUP_COMPANY
    {
        public string company_code { get; set; }
        public string company_name { get; set; }
        public string mobile_no { get; set; }
        public string maker { get; set; }
        public Nullable<System.DateTime> mak_dt { get; set; }
        public Nullable<int> record_id { get; set; }
        public string addresss { get; set; }
    }
}
